version: "3.8"
services:
  mailjet:
    image: axllent/mailpit:latest
    container_name: mailpit
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      - MP_MAX_MESSAGE=5000
